export type WhyPanel = {
  slug: string;
  title: string;
  mistake: string;
  whyItFails: string;
  whyItWorks: string;
  anchor?: string;
  visual?: 'number-line' | 'decimal-grid' | 'fraction-bars' | 'balance' | 'unit-squares' | 'trig-triangle' | 'inertia' | 'equilibrium';
};

const defaultWhyAnchor = 'b-concept-introduction';

export const whyPanels: WhyPanel[] = [
  {
    slug: 'chapter-a1-numbers-and-the-number-line',
    title: 'Why place value and the number line agree',
    mistake: 'A common mistake is treating digits as loose marks, so 40 feels only a little bigger than 4.',
    whyItFails: 'Counting on the number line shows 40 is 36 steps to the right of 4. Calling it only a little bigger contradicts the already-known act of counting by ones.',
    whyItWorks: 'Place value is bundled counting. One tens digit means one bundle of 10 ones. Since each place is built from equal bundles, the written number and the number-line position always match.',
    visual: 'number-line',
  },
  {
    slug: 'chapter-a2-addition-and-subtraction',
    title: 'Why subtracting a negative moves right',
    mistake: 'The tempting mistake is reading -(-4) as "two minus signs means stay negative." That gives -4.',
    whyItFails: 'Subtraction undoes addition. If 0 - (-4) were -4, then adding -4 back would give -8, not 0, so it does not undo anything.',
    whyItWorks: 'A negative number is a move left. Subtracting means remove that move. Removing a 4-step-left move has the same effect as moving 4 steps right, so -(-4) = 4. The same proof works for every distance.',
    visual: 'number-line',
  },
  {
    slug: 'chapter-a3-multiplication-and-division',
    title: 'Why multiplication and division undo each other',
    mistake: 'A common mistake is dividing only part of a grouped quantity and thinking the whole group was divided.',
    whyItFails: 'If 3 x 4 means three equal groups of 4, dividing by 3 must recover the size of one group. Dividing only one piece changes the group structure.',
    whyItWorks: 'Multiplication makes equal groups; division asks either how many groups or how large each group is. Because both talk about the same equal grouping, each operation reverses the other.',
  },
  {
    slug: 'chapter-a3-multiplication-and-division',
    anchor: 'c-the-math-worked-examples',
    title: 'Why a negative times a negative becomes positive',
    mistake: 'A common beginner mistake is counting the two minus signs and deciding the answer must still be negative.',
    whyItFails: 'The sign rule must stay consistent with patterns we already know. If -3 x 4 = -12, then decreasing the second factor by 1 each step adds 3: -3 x 3 = -9, -3 x 2 = -6, -3 x 1 = -3, -3 x 0 = 0. The next step, -3 x -1, must be 3 or the pattern breaks.',
    whyItWorks: 'A negative factor reverses direction. Multiplying by a negative reverses once; multiplying by another negative reverses again, bringing the direction back to positive.',
    visual: 'number-line',
  },
  {
    slug: 'chapter-a3-multiplication-and-division',
    anchor: 'c-the-math-worked-examples',
    title: 'Why counting decimal places works when multiplying',
    mistake: 'The tempting shortcut is to multiply 12 x 5 = 60 and then write 0.60 or 0.6 without asking what size pieces were multiplied.',
    whyItFails: '1.2 is 12 tenths and 0.05 is 5 hundredths. Tenths times hundredths make thousandths. If the answer were 0.6, then multiplying by 0.05, a tiny part, would keep half of 1.2 instead of taking only five hundredths of it.',
    whyItWorks: 'Ignore the decimal point only long enough to multiply the counting numbers. Then put back the place value. One decimal place times two decimal places means thousandths, so 12 x 5 = 60 thousandths = 0.060 = 0.06.',
    visual: 'decimal-grid',
  },
  {
    slug: 'chapter-a3-multiplication-and-division',
    anchor: 'c-the-math-worked-examples',
    title: 'Why 0.2 x 0.3 = 0.06, not 0.6',
    mistake: 'A common mistake is multiplying 2 x 3 and writing 0.6 because the visible digits make 6.',
    whyItFails: '0.2 means 2 tenths and 0.3 means 3 tenths. The product asks for 3 tenths of 2 tenths. That is far smaller than 6 tenths. A partial amount of 0.2 cannot become 0.6.',
    whyItWorks: 'Tenths times tenths make hundredths. 0.2 x 0.3 = 2/10 x 3/10 = 6/100 = 0.06. The answer has two decimal places because the product is counted in hundredths.',
    visual: 'decimal-grid',
  },
  {
    slug: 'chapter-a3-multiplication-and-division',
    anchor: 'c-the-math-worked-examples',
    title: 'Why dividing by 0.5 makes the answer bigger',
    mistake: 'A beginner may expect division to always make numbers smaller, so 6 divided by 0.5 feels like it should be less than 6.',
    whyItFails: 'Division asks how many divisor-sized pieces fit. Half-size pieces are smaller than whole-size pieces, so more of them fit in the same amount. Six contains twelve halves.',
    whyItWorks: 'Dividing by 0.5 asks, "How many halves are in this?" Each whole has 2 halves, so 6 wholes have 12 halves. That is why 6 / 0.5 = 12.',
  },
  {
    slug: 'chapter-a4-fractions',
    anchor: 'c-the-math-worked-examples',
    title: 'Why fractions need common denominators to add',
    mistake: 'The common mistake is adding tops and bottoms: 1/2 + 1/3 = 2/5.',
    whyItFails: 'Halves and thirds are different-sized pieces. Two fifths is made of fifth-sized pieces, so it does not count the original pieces. A half plus a third is bigger than a half, but 2/5 is smaller than a half.',
    whyItWorks: 'A common denominator cuts both quantities into the same-sized pieces. 1/2 = 3/6 and 1/3 = 2/6, so the total is 5/6. Once the piece size matches, adding counts pieces.',
    visual: 'fraction-bars',
  },
  {
    slug: 'chapter-a4-fractions',
    anchor: 'c-the-math-worked-examples',
    title: 'Why multiplying fractions can make a smaller number',
    mistake: 'A beginner mistake is expecting 1/2 x 1/3 to get bigger because multiplication often sounded like "make more" when we used whole numbers.',
    whyItFails: 'Here multiplication means "part of." One third of one half is not larger than one half; it is a smaller slice inside that half. Getting 2/5 or 1/5 does not match the picture of taking a third of a half.',
    whyItWorks: 'Cut a rectangle into 2 equal vertical parts, then cut it into 3 equal horizontal parts. The overlap of 1 vertical part and 1 horizontal part is 1 little rectangle out of 6. That is why 1/2 x 1/3 = 1/6.',
    visual: 'fraction-bars',
  },
  {
    slug: 'chapter-a4-fractions',
    anchor: 'b-concept-introduction',
    title: 'Why multiplying the top and bottom keeps the same fraction',
    mistake: 'A common mistake is thinking 1/2 and 2/4 are different amounts because the numbers look different.',
    whyItFails: 'If the whole is the same size, cutting every old piece into two smaller equal pieces changes the number of pieces, not the amount shaded. One half becomes two fourths, but the shaded length did not grow.',
    whyItWorks: 'Multiplying numerator and denominator by the same number subdivides each piece equally. The piece names change, but the total shaded amount stays the same.',
    visual: 'fraction-bars',
  },
  {
    slug: 'chapter-a4-fractions',
    anchor: 'c-the-math-worked-examples',
    title: 'Why multiplying fractions means part of a part',
    mistake: 'A common mistake is adding across and writing 2/3 x 4/5 = 6/8, or expecting multiplication to always make the number larger.',
    whyItFails: 'Multiplication by a fraction asks for part of the first amount. Four fifths of two thirds cannot be larger than two thirds because four fifths means not all of it.',
    whyItWorks: 'The numerator counts chosen slices in one direction and the denominator counts all slices in that direction. When two cuts cross, total little pieces are bottom x bottom and chosen overlapping pieces are top x top.',
    visual: 'fraction-bars',
  },
  {
    slug: 'chapter-a4-fractions',
    anchor: 'c-the-math-worked-examples',
    title: 'Why dividing fractions flips only the divisor',
    mistake: 'A common mistake is flipping both fractions, or flipping the first fraction instead of the fraction after the division sign.',
    whyItFails: 'Division asks how many divisor-sized pieces fit inside the dividend. Changing the dividend changes the amount being measured, so it answers a different question.',
    whyItWorks: 'Dividing by a fraction is the same as asking how many of those fractional pieces fit. Multiplying by the reciprocal counts those pieces, so only the divisor flips.',
    visual: 'fraction-bars',
  },
  {
    slug: 'chapter-a4-fractions',
    anchor: 'c-the-math-worked-examples',
    title: 'Why reducing a fraction does not change its value',
    mistake: 'A common mistake is thinking 18/24 becomes smaller when reduced to 3/4 because the numbers are smaller.',
    whyItFails: 'The numerator and denominator shrink together by the same factor. The amount shaded does not shrink; only the size of the pieces being counted changes.',
    whyItWorks: 'Reducing divides both top and bottom by the same number. That joins equal small pieces into larger equal pieces while preserving the same portion of the whole.',
    visual: 'fraction-bars',
  },
  {
    slug: 'chapter-a5-decimals-and-percentages',
    title: 'Why percent means per hundred',
    mistake: 'A common mistake is treating 5% as 5 instead of 0.05.',
    whyItFails: 'Percent means parts per 100. If 5% of 200 were 5 x 200, the result would be 1000, which is larger than the whole when the percent was only a small part.',
    whyItWorks: '5% means 5/100. Dividing by 100 turns percent into a decimal, so 5% = 0.05. Then 0.05 x 200 counts five hundredths of 200.',
    visual: 'decimal-grid',
  },
  {
    slug: 'chapter-a5-decimals-and-percentages',
    anchor: 'c-the-math-worked-examples',
    title: 'Why 0.2 + 0.6 = 0.8, not 0.06 or 0.6',
    mistake: 'A common mistake is lining up the digits without respecting place value, or mixing addition with multiplication and writing 0.06.',
    whyItFails: '0.2 is 2 tenths and 0.6 is 6 tenths. Adding them counts tenths: 2 tenths plus 6 tenths is 8 tenths. Writing 0.06 means 6 hundredths, which is smaller than 0.2, so it cannot be the sum of 0.2 and 0.6.',
    whyItWorks: 'Decimals add by matching place values. Tenths add to tenths, hundredths add to hundredths. Since both numbers are tenths, 0.2 + 0.6 = 0.8.',
    visual: 'decimal-grid',
  },
  {
    slug: 'chapter-a5-decimals-and-percentages',
    anchor: 'c-the-math-worked-examples',
    title: 'Why 0.2 x 0.3 = 0.06, not 0.6',
    mistake: 'A common mistake is multiplying 2 x 3 and writing 0.6 because the digits 2 and 3 make 6.',
    whyItFails: '0.2 means 2 tenths, and 0.3 means 3 tenths. The product asks for 3 tenths of 2 tenths. That is much smaller than 6 tenths. If it were 0.6, then taking only part of 0.2 somehow became three times bigger than 0.2, which does not add up.',
    whyItWorks: 'Tenths times tenths make hundredths. 0.2 x 0.3 = 2/10 x 3/10 = 6/100 = 0.06. The two decimal places come from counting hundredths, not from moving a dot by memory.',
    visual: 'decimal-grid',
  },
  {
    slug: 'chapter-a5-decimals-and-percentages',
    anchor: 'c-the-math-worked-examples',
    title: 'Why moving between decimals and percents works',
    mistake: 'A common mistake is moving the decimal point by memory without knowing whether the number should get bigger or smaller.',
    whyItFails: 'Percent means per hundred. If 0.05 became 50%, that would mean 50 out of 100, which is one half. But 0.05 is only five hundredths, not one half.',
    whyItWorks: 'To write a decimal as percent, ask how many hundredths it is. 0.05 is 5 hundredths, so it is 5%. To write percent as a decimal, divide by 100.',
    visual: 'decimal-grid',
  },
  {
    slug: 'chapter-a5-decimals-and-percentages',
    anchor: 'c-the-math-worked-examples',
    title: 'Why percent increase uses 1.10 instead of 0.10',
    mistake: 'A common mistake is increasing by 10% by multiplying the original by 0.10 and stopping there.',
    whyItFails: 'Multiplying by 0.10 gives only the added part, not the original plus the added part. For 50, 0.10 x 50 = 5, but the increased amount should still include the original 50.',
    whyItWorks: 'A 10% increase means keep 100% of the original and add 10% more. That is 110% total, or 1.10 as a decimal. So 50 x 1.10 = 55.',
    visual: 'decimal-grid',
  },
  {
    slug: 'chapter-a6-powers-roots-and-scientific-notation',
    title: 'Why roots reverse powers',
    mistake: 'A common mistake is thinking the square root of 25 is 12.5 because it halves 25.',
    whyItFails: 'Squaring is not doubling. 5 squared means 5 x 5, not 5 + 5. Halving 25 answers a different question.',
    whyItWorks: 'A square root asks which number multiplied by itself gives the original. Since 5 x 5 = 25, sqrt(25) = 5. This holds because the root reverses the power.',
  },
  {
    slug: 'chapter-a7-order-of-operations-pemdas',
    title: 'Why multiplication before addition is not arbitrary',
    mistake: 'A common mistake is solving 2 + 3 x 4 from left to right and getting 20.',
    whyItFails: '3 x 4 describes three groups of 4. Left-to-right changes the expression into five groups of 4, which is not what was written.',
    whyItWorks: 'Multiplication completes the group count before addition combines totals. That is why 2 + 3 x 4 = 2 + 12 = 14. Parentheses can intentionally change the grouping.',
  },
  {
    slug: 'chapter-a8-estimation-rounding-and-significant-figures',
    title: 'Why rounding must keep the size honest',
    mistake: 'A common mistake is rounding every intermediate step and then trusting the final answer exactly.',
    whyItFails: 'Each rounding step can move the value slightly. Repeating that many times can push the final answer away from the true calculation.',
    whyItWorks: 'Rounding is a controlled approximation. Keeping extra digits during work and rounding at the end keeps the accumulated error small while still reporting only meaningful precision.',
  },
  {
    slug: 'chapter-1-variables-and-expressions',
    title: 'Why a variable is not automatically a value',
    mistake: 'A mistake is seeing x and guessing a number before an equation tells us what x must be.',
    whyItFails: 'If x changes value inside the same expression, the expression no longer describes one quantity. The same symbol must mean the same unknown in that local problem.',
    whyItWorks: 'A variable is a placeholder. Rules that work for all numbers can be written once with a variable, then a specific value can be substituted later.',
  },
  {
    slug: 'chapter-2-linear-equations-one-variable',
    title: 'Why doing the same thing to both sides preserves equality',
    mistake: 'A common mistake is moving a number across the equals sign without using the inverse operation.',
    whyItFails: 'An equals sign says both sides have the same value. If one side changes and the other does not, the balance is broken.',
    whyItWorks: 'Equal quantities changed by the same allowed operation remain equal. Inverse operations isolate the unknown while preserving the original balance.',
    visual: 'balance',
  },
  {
    slug: 'chapter-3-rearranging-formulas',
    title: 'Why formula rearranging is still equation balancing',
    mistake: 'A common mistake is moving symbols around by appearance instead of undoing operations.',
    whyItFails: 'Symbols stand for quantities. Rearranging by appearance can change which quantities multiply, divide, add, or subtract.',
    whyItWorks: 'A formula is an equation. To make a new subject, undo the operations around that subject in reverse order while doing the same operation to both sides.',
  },
  {
    slug: 'chapter-4-units-and-dimensional-analysis',
    title: 'Why units can prove a formula is impossible',
    mistake: 'A common mistake is adding values with unlike units, such as meters plus square meters.',
    whyItFails: 'Meters count length and square meters count area. Adding them is like adding apples and floor tiles; the result has no physical meaning.',
    whyItWorks: 'Every term in a valid addition or equation must describe the same kind of quantity. Unit cancellation and matching expose mistakes before numbers hide them.',
  },
  {
    slug: 'chapter-5-systems-of-equations',
    title: 'Why two unknowns need two independent equations',
    mistake: 'A common mistake is expecting one equation with two unknowns to give one fixed answer.',
    whyItFails: 'One equation with two unknowns usually describes many pairs. For x + y = 10, both 4 and 6 or 3 and 7 work.',
    whyItWorks: 'A second independent equation adds a second condition. The solution is the pair that satisfies both conditions at the same time.',
  },
  {
    slug: 'chapter-6-quadratic-equations',
    title: 'Why quadratics can have two answers',
    mistake: 'A common mistake is expecting every equation to have only one solution.',
    whyItFails: 'A parabola can cross the zero line twice. Ignoring one crossing throws away a value that still makes the equation true.',
    whyItWorks: 'A squared term gives symmetric possibilities. Factoring or the quadratic formula finds the input values where the expression equals zero.',
  },
  {
    slug: 'chapter-7-inequalities',
    title: 'Why multiplying by a negative flips an inequality',
    mistake: 'A common mistake is keeping the inequality sign the same after multiplying by -1.',
    whyItFails: 'Start with 2 < 5. Multiplying both by -1 gives -2 and -5. On the number line, -2 is to the right of -5, so -2 > -5.',
    whyItWorks: 'Multiplying by a negative reflects numbers across zero. Reflection reverses left-right order, so the inequality symbol must flip.',
    visual: 'number-line',
  },
  {
    slug: 'chapter-8-exponents-and-powers',
    title: 'Why exponent rules come from repeated multiplication',
    mistake: 'A common mistake is thinking x^2 times x^3 equals x^6 because 2 times 3 is 6.',
    whyItFails: 'x^2 has two x factors and x^3 has three x factors. Together there are five x factors, not six.',
    whyItWorks: 'When powers with the same base multiply, their factor chains join. x^2 x x^3 = x^5, so exponents add because they count factors.',
  },
  {
    slug: 'chapter-9-introduction-to-functions',
    title: 'Why one input must give one output in a function',
    mistake: 'A common mistake is letting the same input produce two different outputs and still calling it one function.',
    whyItFails: 'If one beam position x gave two different moment values in the same model, the diagram would not tell you what the moment is there.',
    whyItWorks: 'A function is a rule with a dependable output for each allowed input. That dependability lets graphs, tables, and formulas describe the same relationship.',
  },
  {
    slug: 'chapter-11-equilibrium-and-the-sum-of-forces',
    title: 'Why equilibrium sums to zero',
    mistake: 'A common mistake is adding only the downward loads and forgetting the upward reactions.',
    whyItFails: 'If the total vertical force is not zero, the object would accelerate up or down. That contradicts the idea of a structure standing still.',
    whyItWorks: 'A still structure has no net push in any direction. Therefore upward and downward forces, and left and right forces, must balance to zero.',
    visual: 'equilibrium',
  },
  {
    slug: 'chapter-12-moments-rotational-forces',
    title: 'Why moment depends on distance',
    mistake: 'A common mistake is using only force and ignoring how far it is from the point of rotation.',
    whyItFails: 'The same push near a hinge barely rotates a door, while the same push far from the hinge rotates it easily. Force alone cannot explain the difference.',
    whyItWorks: 'Moment measures rotational effect: force times perpendicular distance. Distance matters because it is the lever arm that turns a straight push into rotation.',
  },
  {
    slug: 'chapter-15-internal-forces-axial-shear-and-bending-moment',
    title: 'Why a cut reveals internal force',
    mistake: 'A common mistake is thinking internal forces are extra loads added to the structure.',
    whyItFails: 'If the cut piece is isolated and the internal forces are omitted, that piece will not satisfy equilibrium. The missing forces are not optional.',
    whyItWorks: 'Cutting exposes the actions that the removed part used to apply. Those internal actions must balance the isolated piece, so equilibrium reveals them.',
  },
  {
    slug: 'chapter-16-stress-and-strain',
    title: 'Why stress is force divided by area',
    mistake: 'A common mistake is comparing axial force alone without considering member area.',
    whyItFails: 'The same force spread over a large area is gentler than the same force concentrated on a small area. Force alone misses concentration.',
    whyItWorks: 'Stress measures force intensity. Dividing force by area gives load per unit area, which is why larger area lowers stress for the same axial force.',
  },
  {
    slug: 'chapter-18-areas-and-perimeters',
    title: 'Why area is square units',
    mistake: 'A common mistake is measuring area in plain length units, such as saying a rectangle area is 12 m.',
    whyItFails: 'Area counts little squares. A 3 m by 4 m rectangle can be tiled by 12 squares that are each 1 m by 1 m. Calling it 12 m counts a line, not a surface.',
    whyItWorks: 'Length times length makes square units. That is why A = b h has units m x m = m^2. The same unit logic holds for every area formula.',
    visual: 'unit-squares',
  },
  {
    slug: 'chapter-20-moment-of-inertia-second-moment-of-area',
    title: 'Why distance from the neutral axis matters so much',
    mistake: 'A common mistake is thinking two sections with the same area must have the same bending stiffness.',
    whyItFails: 'Bending stretches one side and compresses the other. Material near the neutral axis barely stretches, so putting all area near the middle wastes stiffness.',
    whyItWorks: 'Moment of inertia weights area by distance squared from the neutral axis. Moving material farther away increases stiffness quickly.',
    visual: 'inertia',
  },
  {
    slug: 'chapter-22-right-triangle-trigonometry',
    title: 'Why sine and cosine split a force correctly',
    mistake: 'A common mistake is swapping sine and cosine without checking which side is opposite the angle.',
    whyItFails: 'If the angle changes toward horizontal, the horizontal component should grow and the vertical component should shrink. Swapping the ratios can predict the opposite behavior.',
    whyItWorks: 'In a right triangle, cosine uses adjacent over hypotenuse and sine uses opposite over hypotenuse. Force components follow the same triangle, so the ratios preserve the geometry.',
    visual: 'trig-triangle',
  },
  {
    slug: 'chapter-23-the-pythagorean-theorem',
    title: 'Why diagonal length uses squares',
    mistake: 'A common mistake is adding the legs directly and saying the diagonal is a + b.',
    whyItFails: 'Walking 3 m right and 4 m up is not the same as a straight 7 m brace. The straight diagonal is shorter than the path around the corner.',
    whyItWorks: 'The squares on the two legs exactly combine to the square on the hypotenuse in a right triangle. That geometric area fact gives c^2 = a^2 + b^2.',
  },
  {
    slug: 'chapter-26-polynomials-and-the-bending-moment-equation',
    title: 'Why the bending moment curve is an equation',
    mistake: 'A common mistake is treating a moment diagram as a sketch only, not as values changing along x.',
    whyItFails: 'A sketch cannot reliably tell the exact value at a position unless it comes from a rule. Different sketches could look similar but give different numbers.',
    whyItWorks: 'A polynomial can describe how moment changes with position. Once M(x) is known, every point on the diagram has a calculable value.',
  },
  {
    slug: 'chapter-27-rational-functions-and-proportionality',
    title: 'Why span changes deflection so strongly',
    mistake: 'A common mistake is assuming doubling span only doubles deflection.',
    whyItFails: 'Beam deflection formulas contain powers of span, not just span itself. Linear guessing ignores those repeated span factors.',
    whyItWorks: 'When delta is proportional to L^4, doubling L multiplies delta by 2^4 = 16. Proportionality tells exactly how each input factor scales the output.',
  },
  {
    slug: 'chapter-30-matrices-basic',
    title: 'Why stiffness equations become matrices',
    mistake: 'A common mistake is solving one joint as if it were isolated from the rest of the frame.',
    whyItFails: 'In a connected structure, moving one joint can affect connected members and nearby joints. One isolated equation misses coupling.',
    whyItWorks: 'A matrix stores many linked equations at once. The stiffness matrix relates all chosen displacements to all corresponding forces in one organized system.',
  },
  {
    slug: 'chapter-33-limits-conceptual-introduction',
    title: 'Why a limit is not a guess at one point',
    mistake: 'A common mistake is looking only at the value at the point and ignoring nearby behavior.',
    whyItFails: 'A function can be undefined at a point but still approach a clear value nearby. Looking only at the point misses the approach.',
    whyItWorks: 'A limit asks what value the outputs approach as inputs get closer. This supports slope, derivatives, and mesh convergence because it studies a trend as steps shrink.',
  },
  {
    slug: 'chapter-39-running-the-analysis',
    title: 'Why analysis needs checks after it runs',
    mistake: 'A common mistake is trusting a completed software run just because it produced colored diagrams.',
    whyItFails: 'Software can solve the model you gave it even if supports, loads, stiffness, or units are wrong. A clean run does not prove the model represents the building.',
    whyItWorks: 'Engineering checks compare reactions, deformed shape, periods, and force patterns against expected behavior. Agreement across checks builds confidence that the model and math match.',
  },
];

export function panelsForSlug(slug: string, anchor = defaultWhyAnchor) {
  return whyPanels.filter(panel => panel.slug === slug && (panel.anchor ?? defaultWhyAnchor) === anchor);
}
